---
- name: install jdk
  hosts: sbc 
  remote_user: caiex
  sudo: yes

  tasks:
#  - name: install jdk
#    shell: rpm -e `rpm -qa | grep openjdk` --nodeps

  - name: copy
    copy: src=/tmp/jdk-7u80-linux-x64.tar.gz dest=/tmp

  - name: install begin
    shell: tar zxvf /tmp/jdk-7u80-linux-x64.tar.gz -C /opt

#移动环境变量的方法1
#  - name: set env1
#    copy: src=/etc/profile.d/caiex.sh dest=/tmp

#  - name: set env2
#    shell: cp /tmp/caiex.sh /etc/profile.d/

#移动环境变量的方法2
  - name: set env
    shell: cp /opt/CONF/caiex.sh /etc/profile.d/  

  - name: check jdk
    script: /etc/profile.d/caiex.sh

  - name: update-alternative java
    shell: update-alternatives --install /usr/bin/java java /opt/jdk1.7.0_80/bin/java 300

  - name: update-alternative javac
    shell: update-alternatives --install /usr/bin/javac javac /opt/jdk1.7.0_80/bin/javac 300

  - name: update-alternative jps
    shell: update-alternatives --install /usr/bin/jps jps /opt/jdk1.7.0_80/bin/jps 300

  - name: source profile
    shell: source /etc/profile
